-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public."_user_seq";

CREATE SEQUENCE public."_user_seq"
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.arebbus_user_seq;

CREATE SEQUENCE public.arebbus_user_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.bus_id_seq;

CREATE SEQUENCE public.bus_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.bus_seq;

CREATE SEQUENCE public.bus_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.comment_id_seq;

CREATE SEQUENCE public.comment_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.post_id_seq;

CREATE SEQUENCE public.post_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.post_seq;

CREATE SEQUENCE public.post_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.route_id_seq;

CREATE SEQUENCE public.route_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.route_seq;

CREATE SEQUENCE public.route_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.stop_id_seq;

CREATE SEQUENCE public.stop_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.stop_seq;

CREATE SEQUENCE public.stop_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tag_id_seq;

CREATE SEQUENCE public.tag_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tag_seq;

CREATE SEQUENCE public.tag_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.tag definition

-- Drop table

-- DROP TABLE public.tag;

CREATE TABLE public.tag (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	CONSTRAINT tag_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamp(6) NULL,
	email varchar(255) NOT NULL,
	image varchar(255) NOT NULL,
	latitude numeric(8, 2) NULL,
	longitude numeric(8, 2) NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	reputation int4 NOT NULL,
	updated_at timestamp(6) NULL,
	"valid" bool NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.post definition

-- Drop table

-- DROP TABLE public.post;

CREATE TABLE public.post (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"content" varchar(255) NOT NULL,
	num_upvote int8 NOT NULL,
	author_id int8 NOT NULL,
	CONSTRAINT post_pkey PRIMARY KEY (id),
	CONSTRAINT fk1mpebp1ayl0twrwm7ruiof778 FOREIGN KEY (author_id) REFERENCES public.users(id)
);


-- public.post_tag definition

-- Drop table

-- DROP TABLE public.post_tag;

CREATE TABLE public.post_tag (
	post_id int8 NOT NULL,
	tag_id int8 NOT NULL,
	CONSTRAINT post_tag_pkey PRIMARY KEY (post_id, tag_id),
	CONSTRAINT fkac1wdchd2pnur3fl225obmlg0 FOREIGN KEY (tag_id) REFERENCES public.tag(id),
	CONSTRAINT fkc2auetuvsec0k566l0eyvr9cs FOREIGN KEY (post_id) REFERENCES public.post(id)
);


-- public.route definition

-- Drop table

-- DROP TABLE public.route;

CREATE TABLE public.route (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	author_id int8 NOT NULL,
	CONSTRAINT route_pkey PRIMARY KEY (id),
	CONSTRAINT fkcstw02tmf4wm808dyrb4xmwy6 FOREIGN KEY (author_id) REFERENCES public.users(id)
);


-- public.route_subscription definition

-- Drop table

-- DROP TABLE public.route_subscription;

CREATE TABLE public.route_subscription (
	route_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT route_subscription_pkey PRIMARY KEY (route_id, user_id),
	CONSTRAINT fkerv3v6npaemfn1lbm98w5stx8 FOREIGN KEY (route_id) REFERENCES public.route(id),
	CONSTRAINT fko3h4ls8ijn4tf2pb0apddp6fw FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.stop definition

-- Drop table

-- DROP TABLE public.stop;

CREATE TABLE public.stop (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	latitude numeric(8, 2) NOT NULL,
	longitude numeric(8, 2) NOT NULL,
	"name" varchar(255) NOT NULL,
	author_id int8 NOT NULL,
	CONSTRAINT stop_pkey PRIMARY KEY (id),
	CONSTRAINT fkc5ujjr3urx8b0dfm1pl6ejp7y FOREIGN KEY (author_id) REFERENCES public.users(id)
);


-- public.stop_subscription definition

-- Drop table

-- DROP TABLE public.stop_subscription;

CREATE TABLE public.stop_subscription (
	stop_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT stop_subscription_pkey PRIMARY KEY (stop_id, user_id),
	CONSTRAINT fk9d8cfrbwxbynwyk9m27slx16q FOREIGN KEY (stop_id) REFERENCES public.stop(id),
	CONSTRAINT fkhdyfhy3wgh1gc6io09rbx37lh FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.bus definition

-- Drop table

-- DROP TABLE public.bus;

CREATE TABLE public.bus (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	capacity int2 NOT NULL,
	num_install int4 NOT NULL,
	num_upvote int8 NOT NULL,
	status varchar(255) NULL,
	author_id int8 NOT NULL,
	based_on int8 NULL,
	route_id int8 NOT NULL,
	CONSTRAINT bus_pkey PRIMARY KEY (id),
	CONSTRAINT fk5kq9wmru34yffcw1sst1xlxds FOREIGN KEY (author_id) REFERENCES public.users(id),
	CONSTRAINT fk8njqr6r4pfha7loy5rwir2xkq FOREIGN KEY (based_on) REFERENCES public.bus(id),
	CONSTRAINT fkmrkjerbucw6j8sy8xewrig9wj FOREIGN KEY (route_id) REFERENCES public.route(id)
);


-- public."comment" definition

-- Drop table

-- DROP TABLE public."comment";

CREATE TABLE public."comment" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"content" varchar(255) NOT NULL,
	num_upvote int8 NOT NULL,
	author_id int8 NOT NULL,
	post_id int8 NOT NULL,
	CONSTRAINT comment_pkey PRIMARY KEY (id),
	CONSTRAINT fkir20vhrx08eh4itgpbfxip0s1 FOREIGN KEY (author_id) REFERENCES public.users(id),
	CONSTRAINT fks1slvnkuemjsq2kj4h3vhx7i1 FOREIGN KEY (post_id) REFERENCES public.post(id)
);


-- public.install definition

-- Drop table

-- DROP TABLE public.install;

CREATE TABLE public.install (
	bus_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT install_pkey PRIMARY KEY (bus_id, user_id),
	CONSTRAINT fk61gmy6527nlsif27chuqtkd91 FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkj1layf01ym7r3cryjqf90hr6w FOREIGN KEY (bus_id) REFERENCES public.bus(id)
);


-- public."location" definition

-- Drop table

-- DROP TABLE public."location";

CREATE TABLE public."location" (
	bus_id int8 NOT NULL,
	user_id int8 NOT NULL,
	latitude numeric(8, 2) NOT NULL,
	longitude numeric(8, 2) NOT NULL,
	status varchar(255) NOT NULL,
	"time" timestamp(6) NOT NULL,
	CONSTRAINT location_pkey PRIMARY KEY (bus_id, user_id),
	CONSTRAINT location_status_check CHECK (((status)::text = ANY ((ARRAY['ON_BUS'::character varying, 'WAITING'::character varying, 'LEFT_BUS'::character varying])::text[]))),
	CONSTRAINT fk55by463ivfy1u1qfylnjswyje FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkg69gi3ppfewy568qfaxg5vn42 FOREIGN KEY (bus_id) REFERENCES public.bus(id)
);


-- public.route_stop definition

-- Drop table

-- DROP TABLE public.route_stop;

CREATE TABLE public.route_stop (
	route_id int8 NOT NULL,
	stop_id int8 NOT NULL,
	stop_index int8 NOT NULL,
	CONSTRAINT route_stop_pkey PRIMARY KEY (route_id, stop_id),
	CONSTRAINT fkmu1b9fkhu2d4982t14wc4wjg9 FOREIGN KEY (stop_id) REFERENCES public.stop(id),
	CONSTRAINT fkrah0j8khs716aqhsqt3x5yxbw FOREIGN KEY (route_id) REFERENCES public.route(id)
);


-- public.waiting_for definition

-- Drop table

-- DROP TABLE public.waiting_for;

CREATE TABLE public.waiting_for (
	bus_id int8 NOT NULL,
	user_id int8 NOT NULL,
	"valid" bool NOT NULL,
	CONSTRAINT waiting_for_pkey PRIMARY KEY (bus_id, user_id),
	CONSTRAINT fk4qd9xrhqhjxwslrxbfqfefqab FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkk0bh73kk3ah53je814oak4b0u FOREIGN KEY (bus_id) REFERENCES public.bus(id)
);
