name: Build, Test & Push Docker

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Clean
        run: mvn clean

      - name: Maven Validate
        run: mvn validate

      - name: Maven Compile
        run: mvn compile

      - name: Maven Test
        run: mvn test

      - name: Maven Package
        run: mvn package

      - name: Maven Verify
        run: mvn verify

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker:
    needs: build-test
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push updated version.txt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: downloaded-jar

      - name: Rename for Docker
        run: |
          mkdir -p target
          cp downloaded-jar/*.jar target/app.jar

      - name: Read and bump version
        id: version
        run: |
          VERSION_FILE=version.txt
          OLD_VERSION=$(cat $VERSION_FILE | tr -d 'v')
          NEW_VERSION=$((OLD_VERSION + 1))
          echo "v$NEW_VERSION" > $VERSION_FILE
          echo "VERSION=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit new version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${{ steps.version.outputs.VERSION }}"
          git push origin main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/arebbus-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/arebbus-backend:${{ steps.version.outputs.VERSION }}
